name: ItemShops
author: xQuickGlare
version: 1.0
main: io.alerium.itemshops.ItemShopsPlugin
api-version: 1.15
softdepend: [PlaceholderAPI]
commands: 
  itemshop:
    description: The main command of this plugin